// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChooseAreaSrc: typeof import('./src/components/chooseArea/src/index.vue')['default']
    ChooseIconSrc: typeof import('./src/components/chooseIcon/src/index.vue')['default']
    ContainerSrc: typeof import('./src/components/container/src/index.vue')['default']
    ContainerSrcNavHeader: typeof import('./src/components/container/src/navHeader/index.vue')['default']
    ContainerSrcNavSide: typeof import('./src/components/container/src/navSide/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTag: typeof import('element-plus/es')['ElTag']
    NotificationMenuSrc: typeof import('./src/components/notificationMenu/src/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabListSrc: typeof import('./src/components/tabList/src/index.vue')['default']
    TrendSrc: typeof import('./src/components/trend/src/index.vue')['default']
  }
}
